services:
  frontend:
    image: node:20
    container_name: "sea_battle_frontend"
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend

  backend:
    image: node:20
    container_name: "sea_battle_backend"
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "4000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: "sea_battle_db"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
